[project]
name = "devman-async-lesson4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "aiofiles>=24.1.0",
    "configargparse>=1.7.1",
    "dotenv>=0.9.9",
]

[project.scripts]
view_chat = "chat.scripts.view_chat:main"
connect_chat = "chat.scripts.connect_chat:main"
register_user = "chat.scripts.register_user:main"
send_message = "chat.scripts.send_message:main"
